apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::915924869483:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-15UA8KD5EBHDA
      username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::915924869483:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-31T15:52:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2424"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c79652a4-4744-4886-a05e-56fa4bd0df1f
