apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::915924869483:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-D22C9LA177IC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::915924869483:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-31T02:42:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8005"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 87d2add0-d39e-4955-8051-6f15f9c5e8ce
